pub mod app_state;
pub mod artwork;
pub mod commands;
pub mod config;
mod desktop;
pub mod models;
pub mod network;
pub mod provider_registry;
pub mod providers;
pub mod storage;
pub mod sunshine;
pub mod sync;
pub mod watcher;
pub use desktop::run;
